### ISSUE TITLE
How to specify JIRA backend parameters?

### ISSUE THREAD

**Issue by filmaj** [chaoss/grimoirelab-mordred#121]
Perceval requires that [both a JIRA URL as well as a project key is provided](https://github.com/chaoss/grimoirelab-perceval/blob/master/README.md#jira):

    $ perceval jira 'https://tickets.puppetlabs.com' --project PUP

The [projects file documentation](https://grimoirelab.gitbooks.io/tutorial/content/mordred/the-projects-file.html) is lacking on this topic - the only examples given are for backends that take a single URL as a parameter. What about backends that require multiple parameters? How do I specify that in the projects file?

**Comment by valeriocos** [comment]
Hi @filmaj, thank you for the pointer. We will improve the documentation.

The parameters are specified in a .cfg file (an example is available in the [tests folder](https://github.com/chaoss/grimoirelab-mordred/blob/master/tests/test.cfg)). For any backend, these parameters include information to:
- drive the data uploading and enrichment with GrimoireELK (e.g., raw_index and enriched_index)
- collect data with Perceval. Those parameters have a one-to-one correspondence with the Perceval parameters, which are defined within the file containing the logic of the backend, in the class Command (e.g., [GitHubCommand](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L688), [JiraCommand](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/jira.py#L363)).

An example of a .cfg with more than one parameter is available [here](https://github.com/chaoss/grimoirelab-mordred/blob/master/tests/test.cfg#L108).
In your case, an example of .cfg file for the Jira backend with multiple parameters could look like:
```
...
[jira]
raw_index = jira_test-raw
enriched_index = jira_test
project = a-project-name
max-issues = 10
```

**Comment by filmaj** [comment]
Thanks for the response!

Hmm, so should one specify these things inside the .cfg file, or inside the projects.json file? My current grimoirelab-full docker setup has the .cfg file defining a projects.json file (the [test .cfg file you linked me to](https://github.com/chaoss/grimoirelab-mordred/blob/master/tests/test.cfg#L29) does the same). It looks like both are being used in the test file you linked me to. Does the .cfg file support entering multiple backends of the same type? Or can that only be done in the .json file?

**Comment by valeriocos** [comment]
You're welcome :)
For each backend, the **.json** can contain multiple sources. The data will be extracted from the sources and stored in shared ElasticSearch indexes using the parameters defined in the **.cfg** (e.g., api-token, sleep-for-rate, raw_index, enriched_index). A common example is a list of Git and GitHub repositories of a given organization. For instance, for chaoss, your **.json** and **.cfg** could look like:

**.json**
```
...
"github": [
     "https://github.com/chaoss/grimoirelab-mordred",
     "https://github.com/chaoss/grimoirelab-perceval",
     "https://github.com/chaoss/grimoirelab-elk",
     ...
],
"git": [
     "https://github.com/chaoss/grimoirelab-mordred",
     "https://github.com/chaoss/grimoirelab-perceval",
     "https://github.com/chaoss/grimoirelab-elk",
     ...
],
...
```

**.cfg**
```
...
[github]
     raw_index = github_chaoss-raw
     enriched_index = github_chaoss
     api-token = XXXXX
     sleep-for-rate = true
     ...

[git]
     raw_index = git_chaoss-raw
     enriched_index = git_chaoss
     studies = [enrich_demography]
     ...
...
```

Let me know if this answers your questions.

**Comment by jgbarah** [comment]
> Perceval requires that both a JIRA URL as well as a project key is provided:

I think in fact you can either provide a project key, and then JIRA is mined to get issues for that project, or no project at all, and then JIRA is mined completely.

This said, I'm opening a separate bug report, because I agree that the project, if used, should be in `projects.json` and only there. I'm opening a separate bug report for that because this one could be misleading because the way it was formulated in the first place.

Thanks a lot, @filmaj

**Comment by lukaszgryglicki** [comment]
Well, what if I have multiple combinations? Like say for GitHub:
- I have 4 different repos
- I want to pull issues and pull requests

My understanding would be that I put 4 repos in `projects.json`, and 2 entries in `mordred.cfg` - one for `issue` and the other for `pull_request`, but why do I need to put full repo paths in `projects.json` while `perceval github` expects just `org` and `repo`.

It should call Perceval `4 * 2 = 8` times, right? 4 repos with 2 categories?

Can anybody confirm that my data sources configuration is OK in those two code snippets:

- `mordred.cfg`:
```
projects_file = onos.json
(...)
[git]
raw_index = git_raw
enriched_index = git
category = commit

[github:issue]
api-token = xxx
raw_index = github_raw
enriched_index = github
sleep-for-rate = true
category = issue

[github:pull_request]
api-token = xxx
raw_index = github_raw
enriched_index = github
sleep-for-rate = true
category = pull_request

[gerrit]
user = xxx
raw_index = gerrit_raw
enriched_index = gerrit
category = review

[slack]
raw_index = slack_raw
enriched_index = slack
category = message
api-token = xxx

[jira]
raw_index = jira_raw
enriched_index = jira
category = issue
backend-user = xxx
backend-password = xxx
verify = False

[confluence]
raw_index = confluence_raw
enriched_index = confluence
category = 'historical content'
```

- `onos.json` (especially take a look at GitHub sources definition - Perceval expects `org` `repo`:
```
{
    "ONOS": {
        "git": [
          "https://gerrit.onosproject.org/onos",
          "https://gerrit.onosproject.org/onos-felix",
          "https://gerrit.onosproject.org/spring-open",
          "https://gerrit.onosproject.org/OnosSystemTest",
          "https://gerrit.onosproject.org/onos-loxi",
          "https://gerrit.onosproject.org/onos-yang-tools",
          "https://gerrit.onosproject.org/fabric-control",
          "https://gerrit.onosproject.org/onos-vm",
          "https://gerrit.onosproject.org/onos-app-samples",
          "https://gerrit.onosproject.org/vm-build",
          "https://gerrit.onosproject.org/routing",
          "https://gerrit.onosproject.org/olt-oftest",
          "https://gerrit.onosproject.org/onos-nemo",
          "https://gerrit.onosproject.org/spring-open-cli",
          "https://gerrit.onosproject.org/onos-gerrit-base",
          "https://gerrit.onosproject.org/manifest",
          "https://gerrit.onosproject.org/OnosSystemTestJenkins",
          "https://gerrit.onosproject.org/cord-openwrt"
        ],
        "github": [
          "opennetworkinglab onos",
          "opennetworkinglab spring-open",
          "opennetworkinglab OnosSystemTest",
          "opennetworkinglab onos-loxi",
          "opennetworkinglab onos-yang-tools",
          "opennetworkinglab onos-app-samples",
          "opennetworkinglab routing",
          "opennetworkinglab spring-open-cli"
        ],
        "gerrit": [
          "gerrit.onosproject.org"
        ],
        "slack": [
          "C095YQBM2",
          "C095YQBLL"
        ],
        "jira": [
          "http://jira.onosproject.org"
        ],
        "confluence": [
          "http://wiki.onap.org"
        ]
    }
}
```

Can anybody take a look at other definitions like Arthur etc and confirm that I'm doing this right?
- [mordred.cfg](https://github.com/lukaszgryglicki/bitergia_deployment/blob/master/mordred.cfg.sample)
- [onos.json](https://github.com/lukaszgryglicki/bitergia_deployment/blob/master/onos.json)

@jgbarah @valeriocos

**Comment by lukaszgryglicki** [comment]
And it seems like there is no way to provide SortingHat's autogender API key, tried:
```
autogender = True
autogender_api_token = xxx
```

Also tried - none works:
- autogender_api_token
- autogender_api-token
- autogender-api_token
- autogender-api-token

**Comment by lukaszgryglicki** [comment]
My GitHub data source is not working, I've even changed repos list to be (projects.json):
```
        "github": [
          "https://github.com/httopennetworkinglab/onos",
          "https://github.com/opennetworkinglab/spring-open",
          "https://github.com/opennetworkinglab/OnosSystemTest",
          "https://github.com/opennetworkinglab/onos-loxi",
          "https://github.com/opennetworkinglab/onos-yang-tools",
          "https://github.com/opennetworkinglab/onos-app-samples",
          "https://github.com/opennetworkinglab/routing",
          "https://github.com/opennetworkinglab/spring-open-cli"
        ],
```
and (mordred.cfg):
```
[github:issue]
api-token = xxx
raw_index = github_raw
enriched_index = github
sleep-for-rate = true
category = issue

[github:pull_request]
api-token = xxx
raw_index = github_raw
enriched_index = github
sleep-for-rate = true
category = pull_request
```

What can be wrong?

**Comment by lukaszgryglicki** [comment]
@jgbarah @valeriocos should I open new general issue with questions about configuring Mordred via cfg and json file?

**Comment by valeriocos** [comment]
In the projects.json, you should have:
```
"github:issue": [
          "https://github.com/httopennetworkinglab/onos",
          "https://github.com/opennetworkinglab/spring-open",
          "https://github.com/opennetworkinglab/OnosSystemTest",
          "https://github.com/opennetworkinglab/onos-loxi",
          "https://github.com/opennetworkinglab/onos-yang-tools",
          "https://github.com/opennetworkinglab/onos-app-samples",
          "https://github.com/opennetworkinglab/routing",
          "https://github.com/opennetworkinglab/spring-open-cli"
        ],
"github:pull_request": [
          "https://github.com/httopennetworkinglab/onos",
          "https://github.com/opennetworkinglab/spring-open",
          "https://github.com/opennetworkinglab/OnosSystemTest",
          "https://github.com/opennetworkinglab/onos-loxi",
          "https://github.com/opennetworkinglab/onos-yang-tools",
          "https://github.com/opennetworkinglab/onos-app-samples",
          "https://github.com/opennetworkinglab/routing",
          "https://github.com/opennetworkinglab/spring-open-cli"
        ],
```

The names of the sections in the cfg should have a 1-to-1 correspondence with the keys in the projects.jjson

**Comment by valeriocos** [comment]
yes, good idea @lukaszgryglicki , maybe it's better to have a more generic issue.

**Comment by lukaszgryglicki** [comment]
Created #243
