### ISSUE TITLE
Git Repositories Not Updating 

### ISSUE THREAD

**Issue by Avfdo1994** [chaoss/grimoirelab-mordred#126]
After configuring and setting up the dashboard using mordred, my dashboard is unable to retrieve new data from my git repositories.

**Comment by Avfdo1994** [comment]
Is it necessary to configure author for the dashboard to be updated with new commits from the git repositories or is using just the mordred component enough?

**Comment by sanacl** [comment]
Having the projects.json and mordred up & running will do the update. The frequency depends on the parameter `min_update_delay`. Can u post your setup.cfg so we can help u?

**Comment by Avfdo1994** [comment]
# Config values format
#
# List: [val1, val2 ...]
# Int: int_value
# Int as string: "Int"
# List as string: "[val1, val2 ...]"
# String: string_value
# None: None, none
# Boolean: true, True, False, false

[general]
short_name = Auxenta
update = true
# in seconds
sleep = 0
min_update_delay = 10
debug = true
logs_dir = /home/anthony/Test/logs
bulk_size = 1000
#scroll_size = 100

[projects]
projects_file = projects.json

[es_collection]
url = http://127.0.0.1:9200

[es_enrichment]
url = http://127.0.0.1:9200
autorefresh = false
studies = true

[sortinghat]
host = localhost
user = root
password = 
database = grimoirelab_sh
load_orgs = true
orgs_file = /home/anthony/Test/orgs.json
#see: sortinghat unify --help
#commonly: Unknown
unaffiliated_group = Unknown
affiliate = True
autoprofile = [customer,git,github]
matching = [email]
sleep_for = 0
bots_names = [Beloved Bot]

[panels]
kibiter_time_from= "now-90d"
kibiter_default_index= "git"

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git_test-raw
enriched_index = git_test

**Comment by Avfdo1994** [comment]
I'm pulling commits from a private repository in bitbucket by the way

**Comment by Avfdo1994** [comment]
Is there document that goes into the details of each property in the configuration file?

**Comment by sanacl** [comment]
@Avfdo1994 yep, but the documentation is still very limited https://github.com/chaoss/grimoirelab-mordred/blob/master/doc/config.md

Please change these two parameters, I think your setup is causing a deadlock due to a bug in Mordred.

```
...
min_update_delay = 90
...
sleep_for = 1200
```
And remove this one:
```
sleep = 0
```

Wait for an hour and let us know whether it starting to update the repos. If you want to know the latest modification time of the indexes you can use the tool named indexwarrior (pip install indexwarrior)

**Comment by Avfdo1994** [comment]
@sanacl Is there way to include the password for a private git repository (from bitbucket) in the configuration file?

**Comment by herotest** [comment]
@Sanacl, on the same note can we put a encrypted password?

**Comment by Avfdo1994** [comment]
Resolved this using SSH 
https://confluence.atlassian.com/bitbucket/set-up-an-ssh-key-728138079.html
